/**
 * Loads model definitions from models.json (generated by scripts/fetch_models.ts).
 * Falls back to a single "duo-agentic" model when the file is absent or invalid.
 */

import { fileURLToPath } from "node:url"
import path from "node:path"
import fs from "node:fs"
import { buildModelEntry } from "../shared/model_entry"

type ModelsJsonFile = {
  metadata?: {
    instanceUrl?: string
    rootNamespaceId?: string
    fetchedAt?: string
    defaultModel?: string | null
    pinnedModel?: string | null
    featureFlags?: Record<string, boolean>
  }
  models?: Record<string, Record<string, unknown>>
}

export async function loadGitLabModels(): Promise<Record<string, Record<string, unknown>>> {
  const modelsJsonPath = resolveModelsJsonPath()

  if (modelsJsonPath) {
    try {
      const raw = await fs.promises.readFile(modelsJsonPath, "utf8")
      const data = JSON.parse(raw) as ModelsJsonFile
      if (data.models && Object.keys(data.models).length > 0) {
        console.log(
          `[gitlab-duo] Loaded ${Object.keys(data.models).length} model(s) from ${modelsJsonPath}`,
        )
        return data.models
      }
    } catch (error) {
      console.warn(
        `[gitlab-duo] Failed to read models.json at ${modelsJsonPath}:`,
        error instanceof Error ? error.message : error,
      )
    }
  }

  return {
    "duo-agentic": buildModelEntry("Duo Agentic"),
  }
}

/**
 * Resolve the path to models.json relative to this file's location.
 * Checks the project root (parent of the plugin/ directory).
 */
function resolveModelsJsonPath(): string | null {
  const pluginFilePath = fileURLToPath(import.meta.url)
  const realPluginPath = fs.realpathSync(pluginFilePath)
  const projectRoot = path.resolve(path.dirname(realPluginPath), "..")
  const candidate = path.join(projectRoot, "models.json")
  if (fs.existsSync(candidate)) return candidate
  return null
}
