export const PROVIDER_ID = "gitlab"
export const DEFAULT_MODEL_ID = "duo-chat-sonnet-4-5"
export const DEFAULT_INSTANCE_URL = "https://gitlab.com"
export const CACHE_TTL_MS = 24 * 60 * 60 * 1000
export const WORKFLOW_DEFINITION = "chat"
export const WORKFLOW_CLIENT_VERSION = "1.0"
export const WORKFLOW_ENVIRONMENT = "ide"
export const WORKFLOW_CONNECT_TIMEOUT_MS = 15_000
export const WORKFLOW_HEARTBEAT_INTERVAL_MS = 60_000
export const WORKFLOW_KEEPALIVE_INTERVAL_MS = 45_000
export const WORKFLOW_TOKEN_EXPIRY_BUFFER_MS = 30_000
